#!/bin/bash

gpio -g mode 18 out
lim_temp=44
while true;do
	temp="$(cat /sys/class/thermal/thermal_zone0/temp | awk '{print int($1/1000 + 0.5)}')"
	if [[ "$temp" -gt "$lim_temp" && "$(date "+%H")" -gt "07" ]];then gpio -g write 18 1;lim_temp=38;sleep 1s
	else gpio -g write 18 0;lim_temp=44;sleep 1m;fi
done

