#!/bin/bash

. /home/admin/myproject/huler/on_off_pin

(
while true;do
	temp="$(cat /sys/class/thermal/thermal_zone0/temp | awk '{print int($1/1000 + 0.5)}')"
	if [ "$temp" -gt "40" ];then pin_status 18 1
	else pin_status 18 0;fi
	sleep 1m
done
) &
